### ISSUE TITLE
Have you already pushed this crate to crates.io?

### ISSUE THREAD

**Issue by artorias1024** [woshihaoren4/rush#4]
Hi，I've recently been looking for a rule engine and found your project, it's very useful.

Have you already pushed this crate to crates.io?

**Comment by woshihaoren4** [comment]
no pushed
but  I'll upload it to crate.io within the month.

**Comment by woshihaoren4** [comment]
Pushed to crates.io. Contrast relation:

rush_core--->https://crates.io/crates/rush_core
rush_expr_engine--->https://crates.io/crates/rush_expr_engine
rush_lua_engine--->https://crates.io/crates/rush_lua_engine
rush_wasm_engine--->https://crates.io/crates/rush_wasm_engine
