### ISSUE TITLE
关于flow和规则执行顺序的疑问

### ISSUE THREAD

**Issue by NihilityHsiao** [woshihaoren4/rush#6]
# 遇到的问题
在Rush中的规则不能按顺序执行

# 复现代码
```rust
#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use rush_core::RuleFlow;
    use rush_expr_engine::ExprEngine;
    use serde_json::Value;

    use super::*;

    #[test]
    fn test_rush() {
        let rule_01: &str = r"
        rule to_lowercase
        when
            value != '';
        then
            value = 'rule_01_lowercase';
        ";

        let rule_02: &str = r"
        rule to_uppercase
        when
            value != '';
        then
            value = 'rule_02_uppercase';
        ";

        let rh = Rush::from(Into::<ExprEngine>::into(vec![rule_01, rule_02]));
        let res: HashMap<String, String> = rh
            .flow(r#"{"value":"abc"}"#.parse::<Value>().unwrap())
            .unwrap();
        

        println!("{:?}", res);
    }
}
```

上面这段代码，我期望是按照`rule_01`, `rule_02`的顺序执行
但实际上 `rule_01`和`rule_02`的执行顺序并不是确定的，输出结果可能是`{"value": "rule_01_lowercase"}`， 也可能是 `{"value": "rule_02_uppercase"}`

# 期待效果
希望不同Name的规则也能按顺序执行

**Comment by woshihaoren4** [comment]
之所以这样设计，原因有二：
1. 规则间一但形成执行上的逻辑关系，不利于长时间维护。我之前的某个项目一开始只有10条规则，一年后慢慢维护变成了100条，此时前10条已经不需要了，但之前维护的同事离职了，导致没有人敢去删除这几条废弃规则，最终导致性能越来越差，最终架构重构。
2. 为了一组规则能够快速执行，也就是当Rust变成MutliRush时，会并行执行若干规则。此时无法维护规则间的执行顺序。

不过你的需求很多人给我提过，在同步模式下，让规则顺序执行。我线上的服务很早就改了，这几天我会吧github的代码也同步一下，感谢你的issue。

**Comment by NihilityHsiao** [comment]
了解了，感谢回复

**Comment by fucktx** [comment]
> 之所以这样设计，原因有二：
> 
> 1. 规则间一但形成执行上的逻辑关系，不利于长时间维护。我之前的某个项目一开始只有10条规则，一年后慢慢维护变成了100条，此时前10条已经不需要了，但之前维护的同事离职了，导致没有人敢去删除这几条废弃规则，最终导致性能越来越差，最终架构重构。
> 2. 为了一组规则能够快速执行，也就是当Rust变成MutliRush时，会并行执行若干规则。此时无法维护规则间的执行顺序。
> 
> 不过你的需求很多人给我提过，在同步模式下，让规则顺序执行。我线上的服务很早就改了，这几天我会吧github的代码也同步一下，感谢你的issue。

作者可以留一个微信或者其他联系方式吗

**Comment by woshihaoren4** [comment]
> > 之所以这样设计，原因有二：
> > 
> > 1. 规则间一但形成执行上的逻辑关系，不利于长时间维护。我之前的某个项目一开始只有10条规则，一年后慢慢维护变成了100条，此时前10条已经不需要了，但之前维护的同事离职了，导致没有人敢去删除这几条废弃规则，最终导致性能越来越差，最终架构重构。
> > 2. 为了一组规则能够快速执行，也就是当Rust变成MutliRush时，会并行执行若干规则。此时无法维护规则间的执行顺序。
> > 
> > 不过你的需求很多人给我提过，在同步模式下，让规则顺序执行。我线上的服务很早就改了，这几天我会吧github的代码也同步一下，感谢你的issue。
> 
> 作者可以留一个微信或者其他联系方式吗

上面说的修改已经合进主线了，crate也更新了。
微信号wdzly160319
